; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@CMainWindow@@2UQMetaObject@@B	; CMainWindow::staticMetaObject
PUBLIC	?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CMainWindow::qt_static_metacall
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>
CONST	SEGMENT
$SG105291 DB	'void', 00H
	ORG $+3
$SG138574 DB	'H:\QT\6.0.1\MSVC2019_64\include\QtCore\qmetatype.h', 00H
	ORG $+5
$SG138575 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138576 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@CMainWindow@@2UQMetaObject@@B DQ 0000000000000000H ; CMainWindow::staticMetaObject
	DQ	FLAT:??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
	DQ	FLAT:?qt_meta_stringdata_CMainWindow@@3Uqt_meta_stringdata_CMainWindow_t@@B
	DQ	FLAT:?qt_meta_data_CMainWindow@@3QBIB
	DQ	FLAT:?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	FLAT:??$qt_incomplete_metaTypeArray@Uqt_meta_stringdata_CMainWindow_t@@U?$TypeAndForceComplete@XU?$integral_constant@_N$0A@@std@@@QtPrivate@@U23@U23@U23@U23@U23@U23@U?$TypeAndForceComplete@AEBVQItemSelection@@U?$integral_constant@_N$0A@@std@@@3@U43@U23@U23@U23@U23@U23@U23@U23@@@3QBQEBVQMetaTypeInterface@QtPrivate@@B
	DQ	0000000000000000H
?qt_meta_stringdata_CMainWindow@@3Uqt_meta_stringdata_CMainWindow_t@@B DD 098H ; qt_meta_stringdata_CMainWindow
	DD	0bH
	DD	0a4H
	DD	0dH
	DD	0b2H
	DD	00H
	DD	0b3H
	DD	0dH
	DD	0c1H
	DD	0fH
	DD	0d1H
	DD	0cH
	DD	0deH
	DD	0fH
	DD	0eeH
	DD	0fH
	DD	0feH
	DD	014H
	DD	0113H
	DD	0eH
	DD	0122H
	DD	08H
	DD	012bH
	DD	0aH
	DD	0136H
	DD	012H
	DD	0149H
	DD	013H
	DD	015dH
	DD	012H
	DD	0170H
	DD	01dH
	DD	018eH
	DD	015H
	DD	01a4H
	DD	016H
	DD	01bbH
	DD	017H
	DB	043H
	DB	04dH
	DB	061H
	DB	069H
	DB	06eH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	04fH
	DB	072H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	053H
	DB	061H
	DB	076H
	DB	065H
	DB	04fH
	DB	072H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	053H
	DB	061H
	DB	076H
	DB	065H
	DB	041H
	DB	073H
	DB	04fH
	DB	072H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	04eH
	DB	065H
	DB	077H
	DB	04fH
	DB	072H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	04eH
	DB	065H
	DB	077H
	DB	043H
	DB	075H
	DB	073H
	DB	074H
	DB	06fH
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	044H
	DB	065H
	DB	06cH
	DB	043H
	DB	075H
	DB	073H
	DB	074H
	DB	06fH
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	074H
	DB	06fH
	DB	06dH
	DB	065H
	DB	072H
	DB	00H
	DB	051H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	00H
	DB	073H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	064H
	DB	065H
	DB	073H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	045H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	04eH
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	045H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	050H
	DB	068H
	DB	06fH
	DB	06eH
	DB	065H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	045H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	041H
	DB	064H
	DB	064H
	DB	072H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	045H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	050H
	DB	065H
	DB	072H
	DB	063H
	DB	065H
	DB	06eH
	DB	074H
	DB	061H
	DB	067H
	DB	065H
	DB	050H
	DB	072H
	DB	069H
	DB	063H
	DB	065H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	050H
	DB	061H
	DB	079H
	DB	06dH
	DB	065H
	DB	06eH
	DB	074H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	045H
	DB	06eH
	DB	074H
	DB	065H
	DB	072H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	04dH
	DB	065H
	DB	065H
	DB	074H
	DB	054H
	DB	069H
	DB	06dH
	DB	065H
	DB	00H
	DB	055H
	DB	073H
	DB	065H
	DB	072H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	043H
	DB	075H
	DB	073H
	DB	04dH
	DB	065H
	DB	065H
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	065H
	DB	00H
	ORG $+1
$SG139025 DB	'%s', 00H
	ORG $+1
$SG139024 DB	'invalid argument', 00H
	ORG $+7
?qt_meta_data_CMainWindow@@3QBIB DD 09H			; qt_meta_data_CMainWindow
	DD	00H
	DD	00H
	DD	00H
	DD	0eH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	062H
	DD	02H
	DD	0aH
	DD	00H
	DD	03H
	DD	00H
	DD	063H
	DD	02H
	DD	0aH
	DD	01H
	DD	04H
	DD	00H
	DD	064H
	DD	02H
	DD	0aH
	DD	02H
	DD	05H
	DD	00H
	DD	065H
	DD	02H
	DD	0aH
	DD	03H
	DD	06H
	DD	00H
	DD	066H
	DD	02H
	DD	0aH
	DD	04H
	DD	07H
	DD	00H
	DD	067H
	DD	02H
	DD	0aH
	DD	05H
	DD	08H
	DD	02H
	DD	068H
	DD	02H
	DD	0aH
	DD	06H
	DD	0cH
	DD	00H
	DD	06dH
	DD	02H
	DD	0aH
	DD	09H
	DD	0dH
	DD	00H
	DD	06eH
	DD	02H
	DD	0aH
	DD	0aH
	DD	0eH
	DD	00H
	DD	06fH
	DD	02H
	DD	0aH
	DD	0bH
	DD	0fH
	DD	00H
	DD	070H
	DD	02H
	DD	0aH
	DD	0cH
	DD	010H
	DD	00H
	DD	071H
	DD	02H
	DD	0aH
	DD	0dH
	DD	011H
	DD	00H
	DD	072H
	DD	02H
	DD	0aH
	DD	0eH
	DD	012H
	DD	00H
	DD	073H
	DD	02H
	DD	0aH
	DD	0fH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	080000009H
	DD	080000009H
	DD	0aH
	DD	0bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+12
??$qt_incomplete_metaTypeArray@Uqt_meta_stringdata_CMainWindow_t@@U?$TypeAndForceComplete@XU?$integral_constant@_N$0A@@std@@@QtPrivate@@U23@U23@U23@U23@U23@U23@U?$TypeAndForceComplete@AEBVQItemSelection@@U?$integral_constant@_N$0A@@std@@@3@U43@U23@U23@U23@U23@U23@U23@U23@@@3QBQEBVQMetaTypeInterface@QtPrivate@@B DQ 0000000000000000H ; qt_incomplete_metaTypeArray<qt_meta_stringdata_CMainWindow_t,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<QItemSelection const &,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<QItemSelection const &,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> >,QtPrivate::TypeAndForceComplete<void,std::integral_constant<bool,0> > >
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
	DQ	0000000000000000H
$SG139026 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Ente'
	DB	'rprise\VC\Tools\MSVC\14.26.28801\include\xmemory', 00H
	ORG $+7
$SG139027 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'E', 00H, 'n', 00H, 't', 00H, 'e', 00H, 'r', 00H, 'p', 00H
	DB	'r', 00H, 'i', 00H, 's', 00H, 'e', 00H, '\', 00H, 'V', 00H, 'C'
	DB	00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H
	DB	'\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1'
	DB	00H, '4', 00H, '.', 00H, '2', 00H, '6', 00H, '.', 00H, '2', 00H
	DB	'8', 00H, '8', 00H, '0', 00H, '1', 00H, '\', 00H, 'i', 00H, 'n'
	DB	00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H
	DB	'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y'
	DB	00H, 00H, 00H
	ORG $+14
$SG139028 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG139029 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG131015 DB	'COrderManagerDelegate', 00H
CONST	ENDS
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ ; CMainWindow::metaObject
PUBLIC	?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z	; CMainWindow::qt_metacast
PUBLIC	?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; CMainWindow::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_??0QMetaType@@QEAA@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?UserOpenOrder@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserOpenOrder
EXTRN	?UserSaveOrder@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserSaveOrder
EXTRN	?UserSaveAsOrder@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserSaveAsOrder
EXTRN	?UserNewOrder@CMainWindow@@QEAAXXZ:PROC		; CMainWindow::UserNewOrder
EXTRN	?UserNewCustomer@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserNewCustomer
EXTRN	?UserDelCustomer@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserDelCustomer
EXTRN	?UserSelectedCustomer@CMainWindow@@QEAAXAEBVQItemSelection@@0@Z:PROC ; CMainWindow::UserSelectedCustomer
EXTRN	?UserEnteredCusName@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserEnteredCusName
EXTRN	?UserEnteredCusPhone@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserEnteredCusPhone
EXTRN	?UserEnteredCusAddr@CMainWindow@@QEAAXXZ:PROC	; CMainWindow::UserEnteredCusAddr
EXTRN	?UserEnteredCusPercentagePrice@CMainWindow@@QEAAXXZ:PROC ; CMainWindow::UserEnteredCusPercentagePrice
EXTRN	?UserChangedCusPayment@CMainWindow@@QEAAXXZ:PROC ; CMainWindow::UserChangedCusPayment
EXTRN	?UserEnteredCusMeetTime@CMainWindow@@QEAAXXZ:PROC ; CMainWindow::UserEnteredCusMeetTime
EXTRN	?UserSelectedCusMeetDate@CMainWindow@@QEAAXXZ:PROC ; CMainWindow::UserSelectedCusMeetDate
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
pdata	SEGMENT
$pdata$?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z DD imagerel $LN8
	DD	imagerel $LN8+136
	DD	imagerel $unwind$?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+207
	DD	imagerel $unwind$?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN22
	DD	imagerel $LN22+368
	DD	imagerel $unwind$?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0620eH
$unwind$?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 021801H
	DD	070145218H
$unwind$?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>, COMDAT
; File H:\QT\6.0.1\MSVC2019_64\include\QtCore\qobjectdefs.h
; Line 398
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
; Line 399
	ret	0
??$staticMetaObject@$1?staticMetaObject@QMainWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QMainWindow::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; CMainWindow::qt_static_metacall
; File H:\Nougat\app\NougatWin32\debug\moc\moc_CMainWindow.cpp
; Line 114
$LN22:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 115
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 116
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 13
	ja	$LN19@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN21@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 119
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserOpenOrder@CMainWindow@@QEAAXXZ	; CMainWindow::UserOpenOrder
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 120
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserSaveOrder@CMainWindow@@QEAAXXZ	; CMainWindow::UserSaveOrder
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 121
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserSaveAsOrder@CMainWindow@@QEAAXXZ	; CMainWindow::UserSaveAsOrder
	jmp	$LN2@qt_static_
$LN8@qt_static_:
; Line 122
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserNewOrder@CMainWindow@@QEAAXXZ	; CMainWindow::UserNewOrder
	jmp	$LN2@qt_static_
$LN9@qt_static_:
; Line 123
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserNewCustomer@CMainWindow@@QEAAXXZ	; CMainWindow::UserNewCustomer
	jmp	$LN2@qt_static_
$LN10@qt_static_:
; Line 124
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserDelCustomer@CMainWindow@@QEAAXXZ	; CMainWindow::UserDelCustomer
	jmp	$LN2@qt_static_
$LN11@qt_static_:
; Line 125
	mov	eax, 8
	imul	rax, rax, 2
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	r8, QWORD PTR [rdx+rax]
	mov	rax, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rax+rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserSelectedCustomer@CMainWindow@@QEAAXAEBVQItemSelection@@0@Z ; CMainWindow::UserSelectedCustomer
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 126
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserEnteredCusName@CMainWindow@@QEAAXXZ ; CMainWindow::UserEnteredCusName
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 127
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserEnteredCusPhone@CMainWindow@@QEAAXXZ ; CMainWindow::UserEnteredCusPhone
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 128
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserEnteredCusAddr@CMainWindow@@QEAAXXZ ; CMainWindow::UserEnteredCusAddr
	jmp	SHORT $LN2@qt_static_
$LN15@qt_static_:
; Line 129
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserEnteredCusPercentagePrice@CMainWindow@@QEAAXXZ ; CMainWindow::UserEnteredCusPercentagePrice
	jmp	SHORT $LN2@qt_static_
$LN16@qt_static_:
; Line 130
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserChangedCusPayment@CMainWindow@@QEAAXXZ ; CMainWindow::UserChangedCusPayment
	jmp	SHORT $LN2@qt_static_
$LN17@qt_static_:
; Line 131
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserEnteredCusMeetTime@CMainWindow@@QEAAXXZ ; CMainWindow::UserEnteredCusMeetTime
	jmp	SHORT $LN2@qt_static_
$LN18@qt_static_:
; Line 132
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?UserSelectedCusMeetDate@CMainWindow@@QEAAXXZ ; CMainWindow::UserSelectedCusMeetDate
$LN19@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 136
	add	rsp, 56					; 00000038H
	ret	0
$LN21@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CMainWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
this$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; CMainWindow::qt_metacall
; File H:\Nougat\app\NougatWin32\debug\moc\moc_CMainWindow.cpp
; Line 170
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 48					; 00000030H
; Line 171
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 172
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 173
	mov	eax, DWORD PTR _id$[rsp]
	jmp	$LN1@qt_metacal
$LN2@qt_metacal:
; Line 174
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 175
	cmp	DWORD PTR _id$[rsp], 14
	jge	SHORT $LN5@qt_metacal
; Line 176
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@CMainWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CMainWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 177
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 14
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 178
	cmp	DWORD PTR _c$[rsp], 7
	jne	SHORT $LN6@qt_metacal
; Line 179
	cmp	DWORD PTR _id$[rsp], 14
	jge	SHORT $LN7@qt_metacal
; Line 180
	lea	rax, QWORD PTR $T1[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 8
	rep stosb
	lea	rcx, QWORD PTR $T1[rsp]
	call	QWORD PTR __imp_??0QMetaType@@QEAA@XZ
	mov	rax, QWORD PTR [rax]
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	QWORD PTR [rcx], rax
$LN7@qt_metacal:
; Line 181
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 14
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 183
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 184
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
?qt_metacall@CMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CMainWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv77 = 32
this$ = 64
_clname$ = 72
?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z PROC		; CMainWindow::qt_metacast
; File H:\Nougat\app\NougatWin32\debug\moc\moc_CMainWindow.cpp
; Line 160
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 161
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 162
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_CMainWindow@@3Uqt_meta_stringdata_CMainWindow_t@@B+152
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 163
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 164
	lea	rdx, OFFSET FLAT:$SG131015
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN4@qt_metacas
; Line 165
	cmp	QWORD PTR this$[rsp], 0
	je	SHORT $LN6@qt_metacas
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 40					; 00000028H
	mov	QWORD PTR tv77[rsp], rax
	jmp	SHORT $LN7@qt_metacas
$LN6@qt_metacas:
	mov	QWORD PTR tv77[rsp], 0
$LN7@qt_metacas:
	mov	rax, QWORD PTR tv77[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN4@qt_metacas:
; Line 166
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 167
	add	rsp, 56					; 00000038H
	ret	0
?qt_metacast@CMainWindow@@UEAAPEAXPEBD@Z ENDP		; CMainWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ PROC	; CMainWindow::metaObject
; File H:\Nougat\app\NougatWin32\debug\moc\moc_CMainWindow.cpp
; Line 155
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 156
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+56], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@CMainWindow@@2UQMetaObject@@B ; CMainWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 157
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@CMainWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; CMainWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File H:\QT\6.0.1\MSVC2019_64\include\QtCore\qscopedpointer.h
; Line 116
	mov	QWORD PTR [rsp+8], rcx
; Line 117
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 118
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
